name: docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push frps
        uses: docker/build-push-action@v3
        with:
          context: ./frps
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/frps:latest

      - name: Build and push centos7-py37
        uses: docker/build-push-action@v3
        with:
          context: ./python
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/centos7-py37:${{ steps.date.outputs.date }}
