name: docker
on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y%m%d')"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push frps
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./frps
          push: true
          tags: |
            ghcr.io/zx06/frps:latest
            ghcr.io/zx06/frps:${{ steps.date.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/frps:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/frps:${{ steps.date.outputs.date }}
          
      - name: Build and push baseimage
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./baseimage
          push: true
          tags: |
            ghcr.io/zx06/baseimage:${{ steps.date.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/baseimage:${{ steps.date.outputs.date }}
      
      - name: Build and push deploytools
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./deploytools
          push: true
          tags: |
            ghcr.io/zx06/deploytools:${{ steps.date.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/deploytools:${{ steps.date.outputs.date }}

      - name: Build and push debian-with-utils
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          context: ./debian-with-utils
          push: true
          tags: |
            ghcr.io/zx06/debian-with-utils:${{ steps.date.outputs.date }}
            ${{ secrets.DOCKERHUB_USERNAME }}/debian-with-utils:${{ steps.date.outputs.date }}

      # - name: Build and push centos7-py37
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./python
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/centos7-py37:${{ steps.date.outputs.date }}

      # - name: Build and push centos7-python3.8
      #   uses: docker/build-push-action@v5
      #   with:
      #     context: ./python
      #     file: ./python/Dockerfile.centos7-python3.8
      #     push: true
      #     tags: ${{ secrets.DOCKERHUB_USERNAME }}/centos7-python3.8:${{ steps.date.outputs.date }}

